### ISSUE TITLE
Before program boots, error message displays & program boot halts

### ISSUE THREAD

**Issue by Philip-Sutton** [tweecode/twine#172]
When I try to run Twine 1.4.2, if the previousy opened file uses a custom header that is not in the program's 'targets' folder, the program displays an error message and the program boot halts.

The error message is:

   An error occurred while opening your story.

   Traceback (most recent call last):

   File "app.py, line 103, in open
   File "storyframe.pyo", line 32, in _init_
   File "storyframe.pyo", line 1122, in setTarget
   KeyError: "philip's sugarcane"

I think the program should be written so that if a custom header folder is missing, the program should default to a standard header folder so the program can open.  It might be worth having an error message that alerts the user to the fact that the expected target file is missing - but the program should still open.

**Comment by Philip-Sutton** [comment]
Thanks for fixing this.  

Philip
